### ISSUE TITLE
I've tried just about everything...

### ISSUE THREAD

**Issue by BrotherGrimmy** [Kahmul/SoulsSpeedruns-Save-Organizer#4]
I'm trying to set up the save files so I can practice the bosses for DS3 any% no hit... but nothing I've tried works. I even talked to a streamer who knows a TON about setting it up, and it still loads me up AFTER the fight. Is there a way I can get help in either figuring it out, or if it's a bug?

-Grimmy-
![save organizer stuff](https://user-images.githubusercontent.com/44684377/47879677-961ddc00-ddf7-11e8-8093-20fdd14971dd.PNG)

**Comment by BrotherGrimmy** [comment]
and for the stuff I missed... Java 1.8.0
Win10
Most updated version of souls 3
example:  I quit to game menu at the gundyr fog... import the save... beat gundyr... quit to menu, reload the save... load the specific character and then it puts me right after where I beat gundyr

I really wouldn't mind being able to practice the bosses alone, instead of having to run through the WHOLE game to practice a specific boss

**Comment by Metamaniac** [comment]
"Load Savestate" puts the savestate that the organizer has into the actual game location and replaces the game's save.
"Replace Savestate" takes the current savestate from the game and replaces the version the mod manager has (in that profile).
it's a little unclear but perhaps you were replacing savestates instead of loading them?
